apiVersion: v1
kind: Pod
metadata:
  name: microservice-seguridad-pod
  labels:
    app: microservice-seguridad
    type: microservice
spec:
  containers:
    - name: microservice-seguridad-app
      image: dvboga/serviciosapiseguridad:latest
      ports:
        - containerPort: 80
      env:
        - name: MongoDb__ConnectionString
          value: mongodb://dvboga:$Dvboga@mongo-service:27017