apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
  labels:
   name: mongo-deploy
   app: microservice-libreria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-libreria
      name: mongo-pod
  template:
      metadata:
        name: mongo-pod
        labels:
          app: microservice-libreria
          name: mongo-pod
      spec:
        containers:
          - name: mongo
            image: mongo:4.2.12
            command:
              - /bin/sh
              - -c
            env:
              - name: MONGO_INITDB_ROOT_USERNAME
                value: dvboga
              - name: MONGO_INITDB_ROOT_PASSWORD
                value: "$Dvboga564651**"
            ports:
              - containerPort: 27017
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m" 