apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: microservice-libreria
    name: mongo-pod
spec:
  containers:
    - name: mongo
      image: mongo:4.0
      command:
        - /bin/bash
        - -c
        - sleep
        - "3600000"
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: dvboga
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "$Dvboga"
      ports:
        - containerPort: 27017