apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deploy
  labels:
    name: mongo-deploy
    app: microservice-libreria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-libreria
      name: mongo-pod
  template:
      metadata:
        name: mongo-pod
        labels:
          app: microservice-libreria
          name: mongo-pod
      spec:
        containers:
          - name: mongo
            image: mongo:5.0.25
            command:
              - /bin/sh
              - "-c"
              - "sleep 60m"
            imagePullPolicy: Always
            restartPolicy: Never
            env:
              - name: MONGO_INITDB_ROOT_USERNAME
                value: dvboga
              - name: MONGO_INITDB_ROOT_PASSWORD
                value: "$Dvboga"
            ports:
              - containerPort: 27017