apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: microservice-libreria
    name: mongo-pod
spec:
  containers:
    - name: mongo
      image: mongo:5.0.25
      resources:
        requests:
          memory: "64Mi"  # Solicitar 64 MiB de memoria
          cpu: "250m"     # Solicitar 250 milicores de CPU
        limits:
          memory: "128Mi" # Establecer un límite máximo de 128 MiB de memoria
          cpu: "500m"     # Establecer un límite máximo de 500 milicores de CPU
      command:
        - /bin/bash
        - -c
        - sleep
        - "3600000"
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: dvboga
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "$Dvboga"
      ports:
        - containerPort: 27017