apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: microservice-libreria
    name: mongo-pod
spec:
  containers:
    - name: mongo
      image: mongo:4.2.12
      command:
        - /bin/bash
        - -c
        - mongod
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: dvboga
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "$Dvboga564651**"
      ports:
        - containerPort: 27017